export const ROUTES = {
  HOME: '/',
  HOW_IT_WORKS: '/how-it-works',
  WHO_WE_ARE: '/who-we-are',
  WHY_US: '/why-us',
  SIGN_UP: '/sign-up',
  SIGN_IN: '/sign-in',
  DASHBOARD: '/dashboard',
  TRANSACTIONS: '/dashboard/transactions',
  ACCOUNTS: '/dashboard/accounts',
  INVESTMENTS: '/dashboard/investments',
  CREDIT_CARDS: '/dashboard/cards',
  LOANS: '/dashboard/loans',
  PROFILE: '/dashboard/profile',
  NOTIFICATIONS: '/dashboard/notifications',
  HELP: '/dashboard/help',
}
